### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by 01000110** [nkhdiscovery/AUT-ThesisTemplate#2]
سلام

وقتی عکسی قرار داده می‌شه ۳ تا کپشن براش تولید می‌شه. من نتونستم مشکل رو بفهمم

`\begin{figure}`
`    \includegraphics[width=\textwidth]{Figures/6}`
`    \caption{گراف جهت دار.}`
`\end{figure}‍`

![screenshot from 2017-01-24 13-00-58](https://cloud.githubusercontent.com/assets/15173405/22241616/5a320ec4-e235-11e6-8a7c-6ed6b72310f2.png)
`

**Comment by nkhdiscovery** [comment]
Hi, I will work on it tonight and let you know. 
Can you specify your latex/xetex version?

**Comment by 01000110** [comment]
XeTeX 3.14159265-2.6-0.99996 (TeX Live 2016)

**Comment by nkhdiscovery** [comment]
A total new version of master is ready now, I had to delete previous commits. Please remove your fork and fork master again, it works now. Thanks for tracking this issue. 

سلام، 
باید کامیت‌های فبل پاک می‌شد :دی لطفا فورک قبلی رو پاک کنید و دوباره فورک کنید کل پروژه رو. خیلی بهتر شده، امیدوارم باز هم بهبود پیدا کنه 👍 
سپااس فراون

**Comment by nkhdiscovery** [comment]
Please let me know if this is solved so I can close the issue.

**Comment by 01000110** [comment]
دیگه مشکلی تو کپشن‌ها نیست.
ممنون
