### ISSUE TITLE
مراجع

### ISSUE THREAD

**Issue by 01000110** [nkhdiscovery/AUT-ThesisTemplate#3]
می‌شه برای اضافه کردن مراجع راهنمایی کنید؟
منظورم نوشتن فایل .bib نیست
کامپایل می‌کنم نمیاد!!

**Comment by nkhdiscovery** [comment]
Run :
```bash
bibtex Thesis
```
Where Thesis.bib exists and then recompile the document:
```bash
xelatex Thesis
``` 
You can also use editors, e.g. in gummi you have to select Bibliography tab, press detect and then press compile.

-------
دستورات بالا رو بزنید حل میشه، ممنون از فیدبک ها و سوالات.

**Comment by 01000110** [comment]
حل شد ممنونم
