### ISSUE TITLE
Per page footnote

### ISSUE THREAD

**Issue by ghost** [nkhdiscovery/AUT-ThesisTemplate#6]
I am the author of `xepersian` package, Vafa Khalighi. I am not sure how you reset footnotes per page in your thesis class but since a couple of months ago, `xepersian` has an option, namely `perpagefootnote` which can reset footnote per page. This is done internally by the package `bidi-perpage` which is small and fast and can also reset other counters not just footnote. All you have to do to reset footnotes per page is loading `xepersian` as

```tex
\usepackage[perpagefootnote]{xepersian}
```

Can you and @01000110 (that is where I saw the thesis template originally but I could not contact her) please use this to reset footnotes per page in your thesis template?

**Comment by nkhdiscovery** [comment]
@bidirtex many thanks for reaching out. I am on my way home, and I will test it ASAP. 

By the way, I did not understand what happens when I don't use that option. What is the necessity of using it?

Thanks again :)

**Comment by ghost** [comment]
Generally, it is a requirement in a thesis to reset footnote counters per page so that footnotes start from 1 on each page. What I described above will do exactly this. If you do not use this option or some other packages which reset footnotes per page, then footnotes will be numbered continuously throughout the whole document.

**Comment by ghost** [comment]
You are already doing this in lines 179 and 180 of the file `commands.tex`:

```tex
\usepackage{perpage}
\MakePerPage{footnote}
```

All you have to do is deleting the two lines above and changing line 68 in the same file which is

```tex
\usepackage{xepersian}
```

to 

```tex
\usepackage[perpagefootnote]{xepersian}
```

**Comment by nkhdiscovery** [comment]
Thanks for the explanation. I close this as @01000110 has solved this in her pull request: https://github.com/nkhdiscovery/AUT-ThesisTemplate/commit/7e10304c8384fc00c1ab49c067fe462a08750220

Thank you @01000110 for your contribution.
