### ISSUE TITLE
\setdigitfont has changed

### ISSUE THREAD

**Issue by ghost** [nkhdiscovery/AUT-ThesisTemplate#7]
In old `xepersian`, `\setdigitfont` would change digits in math mode. This has changed since a year ago.

 - To change digits font in math mode, you need to use `\setmathdigitfont`.
 - `\setdigitfont` will change the digits font in both text and math modes.

**Comment by nkhdiscovery** [comment]
Thanks but the usage is still matching as we do not want any Latin character to appear within the Persian text, whether in the math formulas or out of it. 

Thanks for informing; I close this issue.
