### ISSUE TITLE
Have you ever had any issues with the xepersian package?

### ISSUE THREAD

**Issue by ghost** [nkhdiscovery/AUT-ThesisTemplate#8]
Hi

If you ever happen to have any question, then please open an issue at [the `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) and I will be very happy to help out.

Best wishes, Vafa Khalighi (the author of the `xepersian` package)

**Comment by nkhdiscovery** [comment]
Dear @vafakhalighi ! 
Thanks for reaching out! 

Sure I will. We encounter problems with xepersian from time to time but I am too busy to follow up, but I will let you know if we experienced anything fundamental which can be resolved in the xepersian package. :)
